cleaned_spam: data/text_spam_dataset/cleaned_spam.csv
clened_not_spam: data/text_spam_dataset/not_spam.csv
labels_and_scores: data/text_spam_dataset/labels_and_scores.csv
train: data/text_spam_dataset/train.csv
test: data/text_spam_dataset/test.csv
