json_spam_path: dataset/result_spam.json
json_not_spam_path: dataset/result_not_spam.json

spam_path: dataset/spam.csv
not_spam_path: dataset/not_spam.csv
cleaned_spam_path: dataset/cleaned_spam.csv
cleaned_not_spam_path: dataset/cleaned_not_spam.csv

df_cleaned_spam_and_not_spam: dataset/cleaned_spam_and_not_spam.csv
labels_and_scores: dataset/labels_and_scores.csv

train_path: dataset/train.csv
test_path: dataset/test.csv
test_gpt_data_path: data/dataset/test_gpt.csv

stop_words: data/rules_base_model/stop_words.csv
dangerous_words: data/rules_base_model/dangerous_words.csv
spam_words: data/rules_base_model/spam_words.csv
path_not_spam_id: data/rules_base_model/not_spam_id.csv
words_fuzzy_not_enough: data/rules_base_model/words_fuzzy_not_enough.csv